import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import { SITE_CONFIG } from "@/lib/config";

// Register a standard font (optional, but good for stability)
// Font.register({ family: 'Helvetica' });

const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: "Helvetica" },
  header: {
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#E2E8F0",
    paddingBottom: 10,
  },
  brandTitle: {
    fontSize: 22,
    color: "#0F172A",
    fontWeight: "heavy",
    letterSpacing: -0.5,
  },
  brandSubtitle: {
    fontSize: 10,
    color: "#3B82F6",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 2,
  },
  section: { margin: 10, padding: 10 },
  item: { fontSize: 12, marginBottom: 8, flexDirection: "row" },
  bullet: { width: 10, fontSize: 12 },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: "center",
    fontSize: 10,
    color: "grey",
  },
});

type ChecklistProps = {
  permitType: string;
  items: string[];
};

export const ChecklistDocument = ({ permitType, items }: ChecklistProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View>
          <Text style={styles.brandTitle}>{SITE_CONFIG.name}</Text>
          <Text style={styles.brandSubtitle}>
            Intelligent Bureaucracy Engine
          </Text>
        </View>
        <View>
          <Text style={{ fontSize: 10, color: "#64748B" }}>
            Ref: {permitType.toUpperCase()}-{new Date().getFullYear()}
          </Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={{ fontSize: 14, marginBottom: 20, textAlign: "center" }}>
          Type: {permitType}
        </Text>

        {/* The List Items */}
        {items.map((item, i) => (
          <View key={i} style={styles.item}>
            <Text style={styles.bullet}>•</Text>
            <Text>{item}</Text>
          </View>
        ))}
      </View>

      <Text style={styles.footer}>
        Generated by {SITE_CONFIG.name} - strictly based on 2025 Decree Laws.
      </Text>
    </Page>
  </Document>
);
